services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py checksuperuserexists && python manage.py runserver 0.0.0.0:8000 & daphne -b 0.0.0.0 -p 8001 main.asgi:application"
    ports:
      - "8000:8000"  # Django development server
      - "8001:8001"  # Daphne (WebSockets)
    depends_on:
      redis:
        condition: service_started
    env_file: 
      - ./.env

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount your updated Nginx config
    depends_on:
      - web
