# Generated by Django 4.0.10 on 2024-01-09 00:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('show', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('file_route', models.CharField(default='assets/games_cards/game.png', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ended', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.game')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A|L][0-9]{8}$')])),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('forgoten_id', models.BooleanField(default=False)),
                ('hash', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('play', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rental.play')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.student')),
            ],
        ),
        migrations.AddField(
            model_name='play',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.student'),
        ),
    ]
