# Generated by Django 5.0.6 on 2024-07-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
