# Generated by Django 5.0.6 on 2024-12-10 19:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('play', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rental.play')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.student')),
            ],
        ),
        migrations.CreateModel(
            name='OwedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('delivered', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('delivery_deadline', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.material')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.student')),
            ],
        ),
        migrations.AddField(
            model_name='sanction',
            name='owed_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanctions', to='rental.owedmaterial'),
        ),
    ]
