# Generated by Django 3.0.7 on 2023-12-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_auto_20231203_2324'),
        ('rental', '0008_auto_20231203_2323'),
    ]

    operations = [
    ]
