name: Django Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    env:
      DEBUG: True

    steps:
      - name: Main actions/checkout@v5
        uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run migrations (if any)
        run: uv run manage.py migrate

      - name: Run tests
        run: uv run manage.py test
